name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate SBOM
      run: |
        pip install cyclonedx-bom
        cyclonedx-bom --pip --format json -o bom.json

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.4

    - name: Build and push containers
      run: |
        set -axe

        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        TAG=${{ steps.branch-name.outputs.current_branch }} make .image docker-build docker-push

    - uses: sigstore/cosign-installer@main

    - name: Sign container image
      run: |
        cosign sign --key env://COSIGN_PRIVATE_KEY $(cat .image)
      env:
        COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_SIGNING_SECRET}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

    - name: Upload bom to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bom.json
        asset_name: bom.json
        tag: ${{ github.ref }}
        overwrite: true
        body: "CycloneDX json output"
